cd(fileparts(mfilename('fullpath')));
clear all;
filename = 'data/jain.txt';
x = load(filename);
d = shapeset2distset(x);
e = pdist(x(:, 1:2), 'euclidean');
f = squareform(e);
err1 = max(max(abs(f - d)));
fprintf('err1: %12.6f\n', err1);
g = squareform(d);
err2 = max(abs(e - g));
fprintf('err2: %12.6f\n', err2);
[h, i] = cmdscale(d);
j = pdist(h, 'euclidean');
err3 = max(max(j - e));
fprintf('err3: %12.6f\n', err3);
[k, m] = mdscale(d, 2, 'criterion', 'metricstress');
n = pdist(k, 'euclidean');
err4 = max(max(n - e));
fprintf('err4: %12.6f\n', err4);
